/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/_teacher'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as Auth_layoutRouteImport } from './routes/auth/__layout'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminStudentsIndexRouteImport } from './routes/_admin/students/index'
import { Route as AdminFacultyIndexRouteImport } from './routes/_admin/faculty/index'
import { Route as AdminClassesIndexRouteImport } from './routes/_admin/classes/index'
import { Route as TeacherTeacherDashboardRouteImport } from './routes/_teacher/teacher/dashboard'
import { Route as TeacherTeacherClassesRouteImport } from './routes/_teacher/teacher/classes'
import { Route as TeacherTeacherAttendanceRouteImport } from './routes/_teacher/teacher/attendance'
import { Route as StudentStudentScheduleRouteImport } from './routes/_student/student/schedule'
import { Route as StudentStudentDashboardRouteImport } from './routes/_student/student/dashboard'
import { Route as StudentStudentAttendanceRouteImport } from './routes/_student/student/attendance'
import { Route as AdminStudentsCreateRouteImport } from './routes/_admin/students/create'
import { Route as AdminStudentsIdRouteImport } from './routes/_admin/students/$id'
import { Route as AdminFacultyCreateRouteImport } from './routes/_admin/faculty/create'
import { Route as AdminFacultyIdRouteImport } from './routes/_admin/faculty/$id'
import { Route as AdminClassesCreateRouteImport } from './routes/_admin/classes/create'
import { Route as AdminClassesIdRouteImport } from './routes/_admin/classes/$id'
import { Route as TeacherTeacherStudentsIndexRouteImport } from './routes/_teacher/teacher/students/index'
import { Route as AdminStudentsIdIndexRouteImport } from './routes/_admin/students/$id.index'
import { Route as AdminFacultyIdIndexRouteImport } from './routes/_admin/faculty/$id.index'
import { Route as AdminClassesIdIndexRouteImport } from './routes/_admin/classes/$id.index'
import { Route as TeacherTeacherStudentsCreateRouteImport } from './routes/_teacher/teacher/students/create'
import { Route as TeacherTeacherStudentsIdRouteImport } from './routes/_teacher/teacher/students/$id'
import { Route as AdminStudentsIdEditRouteImport } from './routes/_admin/students/$id.edit'
import { Route as AdminStudentsIdAttendanceRouteImport } from './routes/_admin/students/$id.attendance'
import { Route as AdminFacultyIdEditRouteImport } from './routes/_admin/faculty/$id.edit'
import { Route as AdminClassesIdEditRouteImport } from './routes/_admin/classes/$id.edit'
import { Route as TeacherTeacherStudentsIdIndexRouteImport } from './routes/_teacher/teacher/students/$id.index'
import { Route as TeacherTeacherStudentsIdEditRouteImport } from './routes/_teacher/teacher/students/$id.edit'
import { Route as TeacherTeacherStudentsIdAttendanceRouteImport } from './routes/_teacher/teacher/students/$id/attendance'

const TeacherRoute = TeacherRouteImport.update({
  id: '/_teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_layoutRoute = Auth_layoutRouteImport.update({
  id: '/auth/__layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultyIndexRoute = AdminFacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesIndexRoute = AdminClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherTeacherDashboardRoute = TeacherTeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTeacherClassesRoute = TeacherTeacherClassesRouteImport.update({
  id: '/teacher/classes',
  path: '/teacher/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherTeacherAttendanceRoute =
  TeacherTeacherAttendanceRouteImport.update({
    id: '/teacher/attendance',
    path: '/teacher/attendance',
    getParentRoute: () => TeacherRoute,
  } as any)
const StudentStudentScheduleRoute = StudentStudentScheduleRouteImport.update({
  id: '/student/schedule',
  path: '/student/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentDashboardRoute = StudentStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentAttendanceRoute =
  StudentStudentAttendanceRouteImport.update({
    id: '/student/attendance',
    path: '/student/attendance',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminStudentsCreateRoute = AdminStudentsCreateRouteImport.update({
  id: '/students/create',
  path: '/students/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultyCreateRoute = AdminFacultyCreateRouteImport.update({
  id: '/faculty/create',
  path: '/faculty/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultyIdRoute = AdminFacultyIdRouteImport.update({
  id: '/faculty/$id',
  path: '/faculty/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesCreateRoute = AdminClassesCreateRouteImport.update({
  id: '/classes/create',
  path: '/classes/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesIdRoute = AdminClassesIdRouteImport.update({
  id: '/classes/$id',
  path: '/classes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherTeacherStudentsIndexRoute =
  TeacherTeacherStudentsIndexRouteImport.update({
    id: '/teacher/students/',
    path: '/teacher/students/',
    getParentRoute: () => TeacherRoute,
  } as any)
const AdminStudentsIdIndexRoute = AdminStudentsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStudentsIdRoute,
} as any)
const AdminFacultyIdIndexRoute = AdminFacultyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFacultyIdRoute,
} as any)
const AdminClassesIdIndexRoute = AdminClassesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClassesIdRoute,
} as any)
const TeacherTeacherStudentsCreateRoute =
  TeacherTeacherStudentsCreateRouteImport.update({
    id: '/teacher/students/create',
    path: '/teacher/students/create',
    getParentRoute: () => TeacherRoute,
  } as any)
const TeacherTeacherStudentsIdRoute =
  TeacherTeacherStudentsIdRouteImport.update({
    id: '/teacher/students/$id',
    path: '/teacher/students/$id',
    getParentRoute: () => TeacherRoute,
  } as any)
const AdminStudentsIdEditRoute = AdminStudentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminStudentsIdRoute,
} as any)
const AdminStudentsIdAttendanceRoute =
  AdminStudentsIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AdminStudentsIdRoute,
  } as any)
const AdminFacultyIdEditRoute = AdminFacultyIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminFacultyIdRoute,
} as any)
const AdminClassesIdEditRoute = AdminClassesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminClassesIdRoute,
} as any)
const TeacherTeacherStudentsIdIndexRoute =
  TeacherTeacherStudentsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TeacherTeacherStudentsIdRoute,
  } as any)
const TeacherTeacherStudentsIdEditRoute =
  TeacherTeacherStudentsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => TeacherTeacherStudentsIdRoute,
  } as any)
const TeacherTeacherStudentsIdAttendanceRoute =
  TeacherTeacherStudentsIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => TeacherTeacherStudentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/classes/$id': typeof AdminClassesIdRouteWithChildren
  '/classes/create': typeof AdminClassesCreateRoute
  '/faculty/$id': typeof AdminFacultyIdRouteWithChildren
  '/faculty/create': typeof AdminFacultyCreateRoute
  '/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/students/create': typeof AdminStudentsCreateRoute
  '/student/attendance': typeof StudentStudentAttendanceRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/schedule': typeof StudentStudentScheduleRoute
  '/teacher/attendance': typeof TeacherTeacherAttendanceRoute
  '/teacher/classes': typeof TeacherTeacherClassesRoute
  '/teacher/dashboard': typeof TeacherTeacherDashboardRoute
  '/classes/': typeof AdminClassesIndexRoute
  '/faculty/': typeof AdminFacultyIndexRoute
  '/students/': typeof AdminStudentsIndexRoute
  '/classes/$id/edit': typeof AdminClassesIdEditRoute
  '/faculty/$id/edit': typeof AdminFacultyIdEditRoute
  '/students/$id/attendance': typeof AdminStudentsIdAttendanceRoute
  '/students/$id/edit': typeof AdminStudentsIdEditRoute
  '/teacher/students/$id': typeof TeacherTeacherStudentsIdRouteWithChildren
  '/teacher/students/create': typeof TeacherTeacherStudentsCreateRoute
  '/classes/$id/': typeof AdminClassesIdIndexRoute
  '/faculty/$id/': typeof AdminFacultyIdIndexRoute
  '/students/$id/': typeof AdminStudentsIdIndexRoute
  '/teacher/students/': typeof TeacherTeacherStudentsIndexRoute
  '/teacher/students/$id/attendance': typeof TeacherTeacherStudentsIdAttendanceRoute
  '/teacher/students/$id/edit': typeof TeacherTeacherStudentsIdEditRoute
  '/teacher/students/$id/': typeof TeacherTeacherStudentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/auth': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/classes/create': typeof AdminClassesCreateRoute
  '/faculty/create': typeof AdminFacultyCreateRoute
  '/students/create': typeof AdminStudentsCreateRoute
  '/student/attendance': typeof StudentStudentAttendanceRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/schedule': typeof StudentStudentScheduleRoute
  '/teacher/attendance': typeof TeacherTeacherAttendanceRoute
  '/teacher/classes': typeof TeacherTeacherClassesRoute
  '/teacher/dashboard': typeof TeacherTeacherDashboardRoute
  '/classes': typeof AdminClassesIndexRoute
  '/faculty': typeof AdminFacultyIndexRoute
  '/students': typeof AdminStudentsIndexRoute
  '/classes/$id/edit': typeof AdminClassesIdEditRoute
  '/faculty/$id/edit': typeof AdminFacultyIdEditRoute
  '/students/$id/attendance': typeof AdminStudentsIdAttendanceRoute
  '/students/$id/edit': typeof AdminStudentsIdEditRoute
  '/teacher/students/create': typeof TeacherTeacherStudentsCreateRoute
  '/classes/$id': typeof AdminClassesIdIndexRoute
  '/faculty/$id': typeof AdminFacultyIdIndexRoute
  '/students/$id': typeof AdminStudentsIdIndexRoute
  '/teacher/students': typeof TeacherTeacherStudentsIndexRoute
  '/teacher/students/$id/attendance': typeof TeacherTeacherStudentsIdAttendanceRoute
  '/teacher/students/$id/edit': typeof TeacherTeacherStudentsIdEditRoute
  '/teacher/students/$id': typeof TeacherTeacherStudentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/_teacher': typeof TeacherRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/auth/__layout': typeof Auth_layoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/_admin/classes/$id': typeof AdminClassesIdRouteWithChildren
  '/_admin/classes/create': typeof AdminClassesCreateRoute
  '/_admin/faculty/$id': typeof AdminFacultyIdRouteWithChildren
  '/_admin/faculty/create': typeof AdminFacultyCreateRoute
  '/_admin/students/$id': typeof AdminStudentsIdRouteWithChildren
  '/_admin/students/create': typeof AdminStudentsCreateRoute
  '/_student/student/attendance': typeof StudentStudentAttendanceRoute
  '/_student/student/dashboard': typeof StudentStudentDashboardRoute
  '/_student/student/schedule': typeof StudentStudentScheduleRoute
  '/_teacher/teacher/attendance': typeof TeacherTeacherAttendanceRoute
  '/_teacher/teacher/classes': typeof TeacherTeacherClassesRoute
  '/_teacher/teacher/dashboard': typeof TeacherTeacherDashboardRoute
  '/_admin/classes/': typeof AdminClassesIndexRoute
  '/_admin/faculty/': typeof AdminFacultyIndexRoute
  '/_admin/students/': typeof AdminStudentsIndexRoute
  '/_admin/classes/$id/edit': typeof AdminClassesIdEditRoute
  '/_admin/faculty/$id/edit': typeof AdminFacultyIdEditRoute
  '/_admin/students/$id/attendance': typeof AdminStudentsIdAttendanceRoute
  '/_admin/students/$id/edit': typeof AdminStudentsIdEditRoute
  '/_teacher/teacher/students/$id': typeof TeacherTeacherStudentsIdRouteWithChildren
  '/_teacher/teacher/students/create': typeof TeacherTeacherStudentsCreateRoute
  '/_admin/classes/$id/': typeof AdminClassesIdIndexRoute
  '/_admin/faculty/$id/': typeof AdminFacultyIdIndexRoute
  '/_admin/students/$id/': typeof AdminStudentsIdIndexRoute
  '/_teacher/teacher/students/': typeof TeacherTeacherStudentsIndexRoute
  '/_teacher/teacher/students/$id/attendance': typeof TeacherTeacherStudentsIdAttendanceRoute
  '/_teacher/teacher/students/$id/edit': typeof TeacherTeacherStudentsIdEditRoute
  '/_teacher/teacher/students/$id/': typeof TeacherTeacherStudentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth'
    | '/auth/login'
    | '/classes/$id'
    | '/classes/create'
    | '/faculty/$id'
    | '/faculty/create'
    | '/students/$id'
    | '/students/create'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/schedule'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/classes/'
    | '/faculty/'
    | '/students/'
    | '/classes/$id/edit'
    | '/faculty/$id/edit'
    | '/students/$id/attendance'
    | '/students/$id/edit'
    | '/teacher/students/$id'
    | '/teacher/students/create'
    | '/classes/$id/'
    | '/faculty/$id/'
    | '/students/$id/'
    | '/teacher/students/'
    | '/teacher/students/$id/attendance'
    | '/teacher/students/$id/edit'
    | '/teacher/students/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth'
    | '/auth/login'
    | '/classes/create'
    | '/faculty/create'
    | '/students/create'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/schedule'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/classes'
    | '/faculty'
    | '/students'
    | '/classes/$id/edit'
    | '/faculty/$id/edit'
    | '/students/$id/attendance'
    | '/students/$id/edit'
    | '/teacher/students/create'
    | '/classes/$id'
    | '/faculty/$id'
    | '/students/$id'
    | '/teacher/students'
    | '/teacher/students/$id/attendance'
    | '/teacher/students/$id/edit'
    | '/teacher/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_student'
    | '/_teacher'
    | '/_admin/dashboard'
    | '/auth/__layout'
    | '/auth/login'
    | '/_admin/classes/$id'
    | '/_admin/classes/create'
    | '/_admin/faculty/$id'
    | '/_admin/faculty/create'
    | '/_admin/students/$id'
    | '/_admin/students/create'
    | '/_student/student/attendance'
    | '/_student/student/dashboard'
    | '/_student/student/schedule'
    | '/_teacher/teacher/attendance'
    | '/_teacher/teacher/classes'
    | '/_teacher/teacher/dashboard'
    | '/_admin/classes/'
    | '/_admin/faculty/'
    | '/_admin/students/'
    | '/_admin/classes/$id/edit'
    | '/_admin/faculty/$id/edit'
    | '/_admin/students/$id/attendance'
    | '/_admin/students/$id/edit'
    | '/_teacher/teacher/students/$id'
    | '/_teacher/teacher/students/create'
    | '/_admin/classes/$id/'
    | '/_admin/faculty/$id/'
    | '/_admin/students/$id/'
    | '/_teacher/teacher/students/'
    | '/_teacher/teacher/students/$id/attendance'
    | '/_teacher/teacher/students/$id/edit'
    | '/_teacher/teacher/students/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  Auth_layoutRoute: typeof Auth_layoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_teacher': {
      id: '/_teacher'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/__layout': {
      id: '/auth/__layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof Auth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/students/': {
      id: '/_admin/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/faculty/': {
      id: '/_admin/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof AdminFacultyIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/classes/': {
      id: '/_admin/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof AdminClassesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_teacher/teacher/dashboard': {
      id: '/_teacher/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherTeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/_teacher/teacher/classes': {
      id: '/_teacher/teacher/classes'
      path: '/teacher/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherTeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/_teacher/teacher/attendance': {
      id: '/_teacher/teacher/attendance'
      path: '/teacher/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherTeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/_student/student/schedule': {
      id: '/_student/student/schedule'
      path: '/student/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentStudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/dashboard': {
      id: '/_student/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentStudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/attendance': {
      id: '/_student/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentStudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/students/create': {
      id: '/_admin/students/create'
      path: '/students/create'
      fullPath: '/students/create'
      preLoaderRoute: typeof AdminStudentsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/students/$id': {
      id: '/_admin/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/faculty/create': {
      id: '/_admin/faculty/create'
      path: '/faculty/create'
      fullPath: '/faculty/create'
      preLoaderRoute: typeof AdminFacultyCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/faculty/$id': {
      id: '/_admin/faculty/$id'
      path: '/faculty/$id'
      fullPath: '/faculty/$id'
      preLoaderRoute: typeof AdminFacultyIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/classes/create': {
      id: '/_admin/classes/create'
      path: '/classes/create'
      fullPath: '/classes/create'
      preLoaderRoute: typeof AdminClassesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/classes/$id': {
      id: '/_admin/classes/$id'
      path: '/classes/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof AdminClassesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_teacher/teacher/students/': {
      id: '/_teacher/teacher/students/'
      path: '/teacher/students'
      fullPath: '/teacher/students/'
      preLoaderRoute: typeof TeacherTeacherStudentsIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/_admin/students/$id/': {
      id: '/_admin/students/$id/'
      path: '/'
      fullPath: '/students/$id/'
      preLoaderRoute: typeof AdminStudentsIdIndexRouteImport
      parentRoute: typeof AdminStudentsIdRoute
    }
    '/_admin/faculty/$id/': {
      id: '/_admin/faculty/$id/'
      path: '/'
      fullPath: '/faculty/$id/'
      preLoaderRoute: typeof AdminFacultyIdIndexRouteImport
      parentRoute: typeof AdminFacultyIdRoute
    }
    '/_admin/classes/$id/': {
      id: '/_admin/classes/$id/'
      path: '/'
      fullPath: '/classes/$id/'
      preLoaderRoute: typeof AdminClassesIdIndexRouteImport
      parentRoute: typeof AdminClassesIdRoute
    }
    '/_teacher/teacher/students/create': {
      id: '/_teacher/teacher/students/create'
      path: '/teacher/students/create'
      fullPath: '/teacher/students/create'
      preLoaderRoute: typeof TeacherTeacherStudentsCreateRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/_teacher/teacher/students/$id': {
      id: '/_teacher/teacher/students/$id'
      path: '/teacher/students/$id'
      fullPath: '/teacher/students/$id'
      preLoaderRoute: typeof TeacherTeacherStudentsIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/_admin/students/$id/edit': {
      id: '/_admin/students/$id/edit'
      path: '/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof AdminStudentsIdEditRouteImport
      parentRoute: typeof AdminStudentsIdRoute
    }
    '/_admin/students/$id/attendance': {
      id: '/_admin/students/$id/attendance'
      path: '/attendance'
      fullPath: '/students/$id/attendance'
      preLoaderRoute: typeof AdminStudentsIdAttendanceRouteImport
      parentRoute: typeof AdminStudentsIdRoute
    }
    '/_admin/faculty/$id/edit': {
      id: '/_admin/faculty/$id/edit'
      path: '/edit'
      fullPath: '/faculty/$id/edit'
      preLoaderRoute: typeof AdminFacultyIdEditRouteImport
      parentRoute: typeof AdminFacultyIdRoute
    }
    '/_admin/classes/$id/edit': {
      id: '/_admin/classes/$id/edit'
      path: '/edit'
      fullPath: '/classes/$id/edit'
      preLoaderRoute: typeof AdminClassesIdEditRouteImport
      parentRoute: typeof AdminClassesIdRoute
    }
    '/_teacher/teacher/students/$id/': {
      id: '/_teacher/teacher/students/$id/'
      path: '/'
      fullPath: '/teacher/students/$id/'
      preLoaderRoute: typeof TeacherTeacherStudentsIdIndexRouteImport
      parentRoute: typeof TeacherTeacherStudentsIdRoute
    }
    '/_teacher/teacher/students/$id/edit': {
      id: '/_teacher/teacher/students/$id/edit'
      path: '/edit'
      fullPath: '/teacher/students/$id/edit'
      preLoaderRoute: typeof TeacherTeacherStudentsIdEditRouteImport
      parentRoute: typeof TeacherTeacherStudentsIdRoute
    }
    '/_teacher/teacher/students/$id/attendance': {
      id: '/_teacher/teacher/students/$id/attendance'
      path: '/attendance'
      fullPath: '/teacher/students/$id/attendance'
      preLoaderRoute: typeof TeacherTeacherStudentsIdAttendanceRouteImport
      parentRoute: typeof TeacherTeacherStudentsIdRoute
    }
  }
}

interface AdminClassesIdRouteChildren {
  AdminClassesIdEditRoute: typeof AdminClassesIdEditRoute
  AdminClassesIdIndexRoute: typeof AdminClassesIdIndexRoute
}

const AdminClassesIdRouteChildren: AdminClassesIdRouteChildren = {
  AdminClassesIdEditRoute: AdminClassesIdEditRoute,
  AdminClassesIdIndexRoute: AdminClassesIdIndexRoute,
}

const AdminClassesIdRouteWithChildren = AdminClassesIdRoute._addFileChildren(
  AdminClassesIdRouteChildren,
)

interface AdminFacultyIdRouteChildren {
  AdminFacultyIdEditRoute: typeof AdminFacultyIdEditRoute
  AdminFacultyIdIndexRoute: typeof AdminFacultyIdIndexRoute
}

const AdminFacultyIdRouteChildren: AdminFacultyIdRouteChildren = {
  AdminFacultyIdEditRoute: AdminFacultyIdEditRoute,
  AdminFacultyIdIndexRoute: AdminFacultyIdIndexRoute,
}

const AdminFacultyIdRouteWithChildren = AdminFacultyIdRoute._addFileChildren(
  AdminFacultyIdRouteChildren,
)

interface AdminStudentsIdRouteChildren {
  AdminStudentsIdAttendanceRoute: typeof AdminStudentsIdAttendanceRoute
  AdminStudentsIdEditRoute: typeof AdminStudentsIdEditRoute
  AdminStudentsIdIndexRoute: typeof AdminStudentsIdIndexRoute
}

const AdminStudentsIdRouteChildren: AdminStudentsIdRouteChildren = {
  AdminStudentsIdAttendanceRoute: AdminStudentsIdAttendanceRoute,
  AdminStudentsIdEditRoute: AdminStudentsIdEditRoute,
  AdminStudentsIdIndexRoute: AdminStudentsIdIndexRoute,
}

const AdminStudentsIdRouteWithChildren = AdminStudentsIdRoute._addFileChildren(
  AdminStudentsIdRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminClassesIdRoute: typeof AdminClassesIdRouteWithChildren
  AdminClassesCreateRoute: typeof AdminClassesCreateRoute
  AdminFacultyIdRoute: typeof AdminFacultyIdRouteWithChildren
  AdminFacultyCreateRoute: typeof AdminFacultyCreateRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRouteWithChildren
  AdminStudentsCreateRoute: typeof AdminStudentsCreateRoute
  AdminClassesIndexRoute: typeof AdminClassesIndexRoute
  AdminFacultyIndexRoute: typeof AdminFacultyIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminClassesIdRoute: AdminClassesIdRouteWithChildren,
  AdminClassesCreateRoute: AdminClassesCreateRoute,
  AdminFacultyIdRoute: AdminFacultyIdRouteWithChildren,
  AdminFacultyCreateRoute: AdminFacultyCreateRoute,
  AdminStudentsIdRoute: AdminStudentsIdRouteWithChildren,
  AdminStudentsCreateRoute: AdminStudentsCreateRoute,
  AdminClassesIndexRoute: AdminClassesIndexRoute,
  AdminFacultyIndexRoute: AdminFacultyIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentStudentAttendanceRoute: typeof StudentStudentAttendanceRoute
  StudentStudentDashboardRoute: typeof StudentStudentDashboardRoute
  StudentStudentScheduleRoute: typeof StudentStudentScheduleRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentAttendanceRoute: StudentStudentAttendanceRoute,
  StudentStudentDashboardRoute: StudentStudentDashboardRoute,
  StudentStudentScheduleRoute: StudentStudentScheduleRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherTeacherStudentsIdRouteChildren {
  TeacherTeacherStudentsIdAttendanceRoute: typeof TeacherTeacherStudentsIdAttendanceRoute
  TeacherTeacherStudentsIdEditRoute: typeof TeacherTeacherStudentsIdEditRoute
  TeacherTeacherStudentsIdIndexRoute: typeof TeacherTeacherStudentsIdIndexRoute
}

const TeacherTeacherStudentsIdRouteChildren: TeacherTeacherStudentsIdRouteChildren =
  {
    TeacherTeacherStudentsIdAttendanceRoute:
      TeacherTeacherStudentsIdAttendanceRoute,
    TeacherTeacherStudentsIdEditRoute: TeacherTeacherStudentsIdEditRoute,
    TeacherTeacherStudentsIdIndexRoute: TeacherTeacherStudentsIdIndexRoute,
  }

const TeacherTeacherStudentsIdRouteWithChildren =
  TeacherTeacherStudentsIdRoute._addFileChildren(
    TeacherTeacherStudentsIdRouteChildren,
  )

interface TeacherRouteChildren {
  TeacherTeacherAttendanceRoute: typeof TeacherTeacherAttendanceRoute
  TeacherTeacherClassesRoute: typeof TeacherTeacherClassesRoute
  TeacherTeacherDashboardRoute: typeof TeacherTeacherDashboardRoute
  TeacherTeacherStudentsIdRoute: typeof TeacherTeacherStudentsIdRouteWithChildren
  TeacherTeacherStudentsCreateRoute: typeof TeacherTeacherStudentsCreateRoute
  TeacherTeacherStudentsIndexRoute: typeof TeacherTeacherStudentsIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherTeacherAttendanceRoute: TeacherTeacherAttendanceRoute,
  TeacherTeacherClassesRoute: TeacherTeacherClassesRoute,
  TeacherTeacherDashboardRoute: TeacherTeacherDashboardRoute,
  TeacherTeacherStudentsIdRoute: TeacherTeacherStudentsIdRouteWithChildren,
  TeacherTeacherStudentsCreateRoute: TeacherTeacherStudentsCreateRoute,
  TeacherTeacherStudentsIndexRoute: TeacherTeacherStudentsIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  Auth_layoutRoute: Auth_layoutRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
